// scripts/runtime/shadcn/oods-checkbox.tsx
import * as React from 'react';
import type { CheckboxProps } from '@oods/components-react';
import { Checkbox } from '@/registry/new-york-v4/ui/checkbox';
import { Label } from '@/registry/new-york-v4/ui/label';

export const OodsCheckbox = React.forwardRef<HTMLInputElement, CheckboxProps>(function OodsCheckbox(
  { id, label, help, description, validation, density = 'comfortable', requiredIndicator, className, style,
    checkboxClassName, checkboxStyle, onChange, onCheckedChange, onUpdate, required, checked, defaultChecked,
    disabled, readOnly, 'aria-describedby': describedBy, 'aria-label': ariaLabel, ...props }, ref,
) {
  const native = React.useRef<HTMLInputElement>(null);
  React.useImperativeHandle(ref, () => native.current!);
  const [local, setLocal] = React.useState(defaultChecked ?? false);
  const selected = checked ?? local;
  const resetting = React.useRef(false);
  React.useEffect(() => {
    const input = native.current;
    const form = input?.form;
    if (!input || !form) return;
    const reset = (event: Event) => {
      // Team checkbox primitives also observe reset. Preserve native reset's lack of change events.
      resetting.current = true;
      queueMicrotask(() => {
        resetting.current = false;
        if (!event.defaultPrevented && checked === undefined) {
          // The browser resets the property without running React's native value setter.
          input.checked = input.checked;
          setLocal(input.checked);
        }
      });
    };
    form.addEventListener('reset', reset, true);
    return () => form.removeEventListener('reset', reset, true);
  }, [checked, props.form]);
  const details = help ?? description;
  const validationId = validation?.id ?? `${id}-validation`;
  const descriptions = [describedBy, details ? `${id}-description` : '', validation?.message ? validationId : ''].filter(Boolean).join(' ') || undefined;
  return <div className={className} style={style} data-density={density} data-validation-state={validation?.state} data-oods-component={undefined} data-oods-adapter="Checkbox">
    <input {...props} id={id} ref={native} type="checkbox" checked={checked} defaultChecked={checked === undefined ? defaultChecked : undefined} disabled={disabled} readOnly={readOnly} required={required}
      className="sr-only" tabIndex={-1} aria-hidden="true" data-oods-component={undefined}
      onChange={event => { onChange?.(event); if (!event.defaultPrevented) { const next = event.currentTarget.checked; if (checked === undefined) setLocal(next); onCheckedChange?.(next); onUpdate?.(next); } }} />
    <div className="flex items-center gap-2">
      <Checkbox id={`${id}-control`} checked={selected} disabled={disabled} required={required} aria-readonly={readOnly || undefined}
        className={checkboxClassName} style={checkboxStyle} aria-label={ariaLabel} aria-describedby={descriptions} aria-invalid={props['aria-invalid'] ?? (validation?.state === 'error' || undefined)}
        onCheckedChange={() => { if (!readOnly && !resetting.current) native.current?.click(); }} />
      <Label htmlFor={`${id}-control`}>{label}{required && requiredIndicator !== null ? requiredIndicator ?? <span aria-hidden="true"> *</span> : null}</Label>
    </div>
    {details ? <p id={`${id}-description`} className="text-sm text-muted-foreground">{details}</p> : null}
    {validation?.message ? <p id={validationId} role={validation.state === 'error' ? 'alert' : 'status'} aria-live={validation.state === 'error' ? 'assertive' : 'polite'}>{validation.message}</p> : null}
  </div>;
});

// scripts/runtime/shadcn-vue/oods-checkbox.vue
<script lang="ts">
import { defineComponent, h, ref, useId } from 'vue';
import { Checkbox as Contract } from '@oods/components-vue';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsCheckboxAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots, emit }: any) {
    const generated = useId(), local = ref(props.defaultChecked), native = ref<HTMLInputElement>();
    const change = (value: boolean | 'indeterminate') => { const next = value === true; if (native.value) { native.value.checked = next; native.value.dispatchEvent(new Event('change', { bubbles: true })); } if (props.modelValue === undefined && props.checked === undefined) local.value = next; emit('update:modelValue', next); emit('change', next); };
    return () => {
      const id = props.id ?? `oods-checkbox-${generated}`, help = slots.help?.() ?? props.help, validation = slots.validation?.() ?? props.validation?.message;
      return h('div', { class: 'grid gap-2', 'data-oods-adapter': 'Checkbox' }, [
        h('input', { id, ref: native, type: 'checkbox', class: 'sr-only', tabIndex: -1, 'aria-hidden': 'true', name: props.name, disabled: props.disabled, required: props.required, checked: props.modelValue ?? props.checked ?? local.value }),
        h('div', { class: 'flex items-center gap-2' }, [h(Checkbox, { ...attrs, 'data-oods-component': undefined, id: id + '-control', required: props.required, disabled: props.disabled,
          modelValue: props.modelValue ?? props.checked ?? local.value, 'onUpdate:modelValue': change,
          'aria-invalid': props.validation?.state === 'error' || undefined, 'aria-describedby': [attrs['aria-describedby'], help ? id + '-help' : '', validation ? id + '-validation' : ''].filter(Boolean).join(' ') || undefined,
        }), h(Label, { for: id + '-control' }, { default: () => [slots.label?.() ?? props.label, props.required ? h('span', { 'aria-hidden': 'true' }, '*') : null] })]),
        help ? h('p', { id: id + '-help', class: 'text-sm' }, help) : null,
        validation ? h('p', { id: id + '-validation', role: props.validation?.state === 'error' ? 'alert' : undefined }, validation) : null,
      ]);
    };
  },
});
</script>
