// scripts/runtime/shadcn/oods-status-badge.tsx
import * as React from 'react';
import type { StatusBadgeProps } from '@oods/components-react';
import { getStatusPresentation, resolveStatusIcon, statusIconMarkup } from '@oods/component-contracts';
import { Badge } from '@/registry/new-york-v4/ui/badge';

export const OodsStatusBadge = React.forwardRef<HTMLSpanElement, StatusBadgeProps>(function OodsStatusBadge(
  { status, value, label, children, content, domain = 'subscription', tone, emphasis = 'subtle', variant,
    showIcon = true, icon, iconPosition = 'start', title, field, statusField, domainField, readOnly, compact,
    'aria-label': ariaLabel, className, ...props }, ref,
) {
  void [field, statusField, domainField, readOnly, compact];
  const state = status ?? value ?? 'unknown';
  const presentation = getStatusPresentation(domain, state);
  const resolvedTone = tone && tone !== 'lifecycle' ? tone : presentation.tone;
  const destructive = resolvedTone === 'critical' || resolvedTone === 'danger';
  const solid = variant === 'solid' || emphasis === 'solid';
  const name = resolveStatusIcon(presentation.iconName);
  const mark = showIcon ? icon ?? (name ? <span aria-hidden="true" dangerouslySetInnerHTML={{ __html: statusIconMarkup(name) }} /> : null) : null;
  const destructiveClass = destructive ? 'bg-destructive text-background dark:bg-destructive [a]:hover:bg-destructive' : undefined;
  return <Badge {...props} role={props.role ?? 'status'} ref={ref} className={[destructiveClass, className].filter(Boolean).join(' ')} variant={destructive ? 'destructive' : solid ? 'default' : 'secondary'}
    data-oods-component={undefined} data-oods-adapter="StatusBadge" data-status={state} data-domain={domain} data-tone={resolvedTone}
    title={title ?? presentation.description} aria-label={ariaLabel ?? label ?? `Status: ${presentation.label}`}>
    {iconPosition === 'start' ? mark : null}{children ?? content ?? presentation.label}{iconPosition === 'end' ? mark : null}
  </Badge>;
});

// scripts/runtime/shadcn-vue/oods-status-badge.vue
<script lang="ts">
import { defineComponent, h } from 'vue';
import { StatusBadge as Contract } from '@oods/components-vue';
import { Badge } from '@/components/ui/badge';
import { getStatusPresentation, resolveStatusIcon, statusIconMarkup } from '@oods/component-contracts';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsStatusBadgeAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots }: any) {
    return () => {
      const status = props.status ?? props.value ?? 'unknown';
      const presentation = getStatusPresentation(props.domain, status);
      const tone = props.tone && props.tone !== 'lifecycle' ? props.tone : presentation.tone;
      const danger = tone === 'critical' || tone === 'danger';
      const icon = resolveStatusIcon(presentation.iconName);
      return h(Badge, { ...attrs, role: attrs.role ?? 'status', 'data-oods-component': undefined, variant: danger ? 'destructive' : props.emphasis === 'solid' || props.variant === 'solid' ? 'default' : 'secondary',
        class: [danger ? 'bg-destructive text-background dark:bg-destructive' : '', attrs.class],
        'data-oods-adapter': 'StatusBadge', 'data-status': status, 'data-tone': tone, 'data-domain': props.domain,
        title: attrs.title ?? presentation.description, 'aria-label': attrs['aria-label'] ?? props.label ?? `Status: ${presentation.label}`,
      }, { default: () => [slots.icon?.() ?? (props.showIcon && icon ? h('span', { 'aria-hidden': 'true', innerHTML: statusIconMarkup(icon) }) : null), slots.default?.() ?? props.content ?? presentation.label] });
    };
  },
});
</script>
