// scripts/runtime/shadcn/oods-button.tsx
import * as React from 'react';
import type { ButtonProps } from '@oods/components-react';
import { Button } from '@/registry/new-york-v4/ui/button';

export const OodsButton = React.forwardRef<HTMLButtonElement, ButtonProps>(function OodsButton(
  { content, children, intent = 'neutral', size = 'md', type, asChild = false, className, onClick, onActivate, ...props }, ref,
) {
  const variant = intent === 'danger' || intent === 'destructive' ? 'destructive'
    : intent === 'primary' ? 'default'
    : intent === 'neutral' ? 'secondary'
    : intent === 'success' || intent === 'warning' ? 'secondary' : intent;
  // Keep normal-size destructive text readable using the team's solid tokens in both themes.
  const destructiveClass = variant === 'destructive' ? 'bg-destructive text-background hover:bg-destructive dark:bg-destructive dark:hover:bg-destructive' : undefined;
  return <Button {...props} ref={ref} className={[destructiveClass, className].filter(Boolean).join(' ')} variant={variant} size={size === 'md' ? 'default' : size === 'xs' ? 'sm' : size}
    asChild={asChild} {...(asChild ? {} : { type: type ?? 'button' })} data-oods-component={undefined} data-oods-adapter="Button"
    data-intent={intent} onClick={event => { onClick?.(event); if (!event.defaultPrevented) onActivate?.(event); }}>
    {children ?? content}
  </Button>;
});

// scripts/runtime/shadcn-vue/oods-button.vue
<script lang="ts">
import { defineComponent, h } from 'vue';
import { Button as Contract } from '@oods/components-vue';
import { Button } from '@/components/ui/button';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsButtonAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots, emit }: any) {
    return () => h(Button, { ...attrs, 'data-oods-component': undefined, type: props.type, disabled: props.disabled,
      variant: ({ primary: 'default', neutral: 'outline', secondary: 'secondary', success: 'secondary', warning: 'secondary', danger: 'destructive', ghost: 'ghost' } as any)[props.intent] ?? 'default',
      size: props.size === 'md' ? 'default' : props.size === 'xs' ? 'sm' : props.size,
      class: [props.intent === 'danger' ? 'bg-destructive text-background hover:bg-destructive dark:bg-destructive dark:hover:bg-destructive' : '', attrs.class],
      'data-oods-adapter': 'Button', onClick: (event: MouseEvent) => emit('activate', event),
    }, { default: () => slots.default?.() ?? props.content });
  },
});
</script>
