// scripts/runtime/shadcn/oods-input.tsx
import * as React from 'react';
import type { InputProps } from '@oods/components-react';
import { dateTimeInputValue } from '@oods/component-contracts';
import { Input } from '@/registry/new-york-v4/ui/input';
import { Label } from '@/registry/new-york-v4/ui/label';

export const OodsInput = React.forwardRef<HTMLInputElement, InputProps>(function OodsInput(
  { id, label, help, description, validation, density = 'comfortable', requiredIndicator, className, style,
    inputClassName, inputStyle, onChange, onValueChange, onUpdate, required, type = 'text', 'aria-describedby': describedBy, ...props }, ref,
) {
  if (type === 'datetime-local') {
    if (props.value !== undefined) props.value = dateTimeInputValue(props.value);
    if (props.defaultValue !== undefined) props.defaultValue = dateTimeInputValue(props.defaultValue);
  }
  const details = help ?? description;
  const validationId = validation?.id ?? `${id}-validation`;
  const descriptions = [describedBy, details ? `${id}-description` : '', validation?.message ? validationId : ''].filter(Boolean).join(' ') || undefined;
  return <div className={className} style={style} data-density={density} data-validation-state={validation?.state} data-oods-component={undefined} data-oods-adapter="Input">
    <Label htmlFor={id}>{label}{required && requiredIndicator !== null ? requiredIndicator ?? <span aria-hidden="true"> *</span> : null}</Label>
    <Input {...props} ref={ref} id={id} type={type} required={required} className={[density === 'compact' ? 'py-1' : '', inputClassName].filter(Boolean).join(' ')} style={inputStyle}
      data-oods-component={undefined} data-validation-state={validation?.state} aria-describedby={descriptions} aria-invalid={props['aria-invalid'] ?? (validation?.state === 'error' || undefined)}
      onChange={event => { onChange?.(event); if (!event.defaultPrevented) { onValueChange?.(event.currentTarget.value); onUpdate?.(event.currentTarget.value); } }} />
    {details ? <p id={`${id}-description`} className="text-sm text-muted-foreground">{details}</p> : null}
    {validation?.message ? <p id={validationId} role={validation.state === 'error' ? 'alert' : 'status'} aria-live={validation.state === 'error' ? 'assertive' : 'polite'}>{validation.message}</p> : null}
  </div>;
});

// scripts/runtime/shadcn-vue/oods-input.vue
<script lang="ts">
import { defineComponent, h, ref, useId } from 'vue';
import { Input as Contract } from '@oods/components-vue';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { dateTimeInputValue } from '@oods/component-contracts';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsInputAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots, emit }: any) {
    const generated = useId(), local = ref(props.defaultValue);
    const update = (value: string | number) => { const next = String(value); if (props.modelValue === undefined && props.value === undefined) local.value = next; emit('update:modelValue', next); emit('input', next); };
    return () => {
      const id = props.id ?? `oods-input-${generated}`, value = props.modelValue ?? props.value ?? local.value;
      const help = slots.help?.() ?? props.help, validation = slots.validation?.() ?? props.validation?.message;
      const described = [attrs['aria-describedby'], help ? id + '-help' : '', validation ? id + '-validation' : ''].filter(Boolean).join(' ') || undefined;
      return h('div', { class: 'grid gap-2', 'data-oods-adapter': 'Input' }, [
        slots.label || props.label ? h(Label, { for: id }, { default: () => [slots.label?.() ?? props.label, props.required ? h('span', { 'aria-hidden': 'true' }, '*') : null] }) : null,
        h(Input, { ...attrs, 'data-oods-component': undefined, id, type: props.type, name: props.name, modelValue: props.type === 'datetime-local' ? dateTimeInputValue(value) : value,
          'onUpdate:modelValue': update, onChange: (event: Event) => emit('change', (event.target as HTMLInputElement).value),
          class: [props.inputClass, attrs.class], rows: props.rows, placeholder: props.placeholder, required: props.required, disabled: props.disabled, readonly: props.readOnly,
          min: props.min, max: props.max, step: props.step, 'aria-invalid': props.validation?.state === 'error' || undefined, 'aria-describedby': described,
          'aria-errormessage': props.validation?.state === 'error' ? id + '-validation' : undefined,
        }),
        help ? h('p', { id: id + '-help', class: 'text-sm' }, help) : null,
        validation ? h('p', { id: id + '-validation', role: props.validation?.state === 'error' ? 'alert' : undefined, class: 'text-sm' }, validation) : null,
      ]);
    };
  },
});
</script>
