// scripts/runtime/shadcn-vue/oods-card-header.vue
<script lang="ts">
import { defineComponent, h, Fragment, Text } from 'vue';
import { CardHeader as Contract } from '@oods/components-vue';
import { CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsCardHeaderAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots }: any) {
    const first = (...values: any[]) => values.find(value => typeof value === 'string' && value.trim());
    const flatten = (nodes: any[]): any[] => nodes.flatMap(node => node.type === Fragment ? flatten(node.children ?? []) : [node]);
    return () => {
      const content = flatten(slots.default?.() ?? []);
      const scalar = content.every(node => node.type === Text) ? content.map(node => node.children).join('') : undefined;
      const title = first(scalar, props.title, props.label, props.text) ?? 'Card';
      const details = first(props.supporting, props.supportingText, props.subtitle, props.description);
      const heading = /^h[1-6]$/.test(props.as ?? '') ? props.as : `h${Number.isFinite(props.level) ? Math.max(1, Math.min(6, Math.trunc(props.level))) : 2}`;
      return h('header', { ...attrs, 'data-oods-component': undefined, 'data-oods-adapter': 'CardHeader' }, [h(CardHeader, {}, { default: () => content.length && scalar === undefined ? content : [
        h(CardTitle, {}, { default: () => h(heading, title) }), details && details.trim() !== title.trim() ? h(CardDescription, {}, { default: () => details }) : null,
      ] })]);
    };
  },
});
</script>

// scripts/runtime/shadcn/oods-card-header.tsx
import * as React from 'react';
import type { CardHeaderProps, HeaderElement } from '@oods/components-react';
import { CardHeader, CardTitle, CardDescription } from '@/registry/new-york-v4/ui/card';

export const OodsCardHeader = React.forwardRef<HTMLElement, CardHeaderProps>(function OodsCardHeader(
  { title, label, text, supporting, supportingText, subtitle, description, level, as, children, className, ...props }, ref,
) {
  const firstText = (...values: Array<string | undefined>) => values.find(value => value?.trim());
  const flatten = (value: React.ReactNode): React.ReactNode[] => React.Children.toArray(value).flatMap(node => React.isValidElement<{ children?: React.ReactNode }>(node) && node.type === React.Fragment ? flatten(node.props.children) : [node]);
  const nodes = flatten(children);
  const authored = nodes.some(node => typeof node !== 'string' && typeof node !== 'number');
  const scalar = authored ? undefined : nodes.join('');
  const heading = scalar?.trim() ? scalar : firstText(title, label, text) ?? 'Card';
  const details = firstText(supporting, supportingText, subtitle, description);
  const Heading = (as && /^h[1-6]$/.test(as) ? as : `h${Number.isFinite(level) ? Math.max(1, Math.min(6, Math.trunc(level!))) : 2}`) as HeaderElement;
  return <header {...props} ref={ref} className={className} data-oods-component={undefined} data-oods-adapter="CardHeader">
    <CardHeader>{authored ? children : <>
      <CardTitle><Heading>{heading}</Heading></CardTitle>
      {details && details.trim() !== heading.trim() ? <CardDescription data-oods-supporting="true">{details}</CardDescription> : null}
    </>}</CardHeader>
  </header>;
});
