// scripts/runtime/shadcn-vue/oods-tabs.vue
<script lang="ts">
import { defineComponent, h, ref } from 'vue';
import { Tabs as Contract } from '@oods/components-vue';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsTabsAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots, emit }: any) {
    const local = ref(props.defaultSelectedId ?? props.items.find((item: any) => !item.disabled && !item.isDisabled)?.id);
    const selected = () => props.items.find((item: any) => item.id === (props.selectedId ?? local.value) && !item.disabled && !item.isDisabled)?.id ?? props.items.find((item: any) => !item.disabled && !item.isDisabled)?.id;
    const change = (value: string | number) => { const id = String(value); if (id === selected()) return; if (props.selectedId === undefined) local.value = id; emit('update:selectedId', id); emit('change', id); };
    return () => h(Tabs, { ...attrs, 'data-oods-component': undefined, modelValue: selected(), 'onUpdate:modelValue': change, 'data-oods-adapter': 'Tabs' }, { default: () => [
      h('div', { class: 'max-w-full overflow-x-auto' }, [h(TabsList, { 'aria-label': props.ariaLabel }, { default: () => props.items.map((item: any) => h(TabsTrigger, {
        value: item.id, disabled: item.disabled || item.isDisabled, 'data-tab-id': item.id,
      }, { default: () => slots.itemLabel?.({ item, selected: item.id === selected() }) ?? item.label })) })]),
      ...props.items.map((item: any) => h(TabsContent, { value: item.id }, { default: () => slots.panel?.({ item, selected: item.id === selected() }) ?? item.panel })),
    ] });
  },
});
</script>

// scripts/runtime/shadcn/oods-tabs.tsx
import * as React from 'react';
import type { TabsProps } from '@oods/components-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/registry/new-york-v4/ui/tabs';

export const OodsTabs = React.forwardRef<HTMLDivElement, TabsProps>(function OodsTabs(
  { items, selectedId, defaultSelectedId, size = 'md', overflowLabel, ariaLabel, onChange, onUpdate, dir, 'aria-label': nativeLabel, ...props }, ref,
) {
  void overflowLabel; // This adapter scrolls the tab list; it has no overflow menu.
  const [local, setLocal] = React.useState(defaultSelectedId ?? items.find(item => !item.disabled && !item.isDisabled)?.id);
  const selected = selectedId ?? local;
  const notified = React.useRef(selected); notified.current = selected;
  const select = (id: string) => {
    if (id === notified.current) return;
    notified.current = id;
    if (selectedId === undefined) setLocal(id);
    onChange?.(id); onUpdate?.(id);
  };
  return <Tabs {...props} ref={ref} value={selected} defaultValue={defaultSelectedId} dir={dir === 'ltr' || dir === 'rtl' ? dir : undefined}
    data-oods-component={undefined} data-oods-adapter="Tabs" data-size={size} onValueChange={select}>
    <div className="max-w-full overflow-x-auto"><TabsList aria-label={ariaLabel ?? nativeLabel}>
      {items.map(item => <TabsTrigger key={item.id} data-tab-id={item.id} value={item.id} disabled={item.disabled || item.isDisabled} onFocus={item.disabled || item.isDisabled ? undefined : () => select(item.id)}
        className={size === 'sm' ? 'text-xs' : size === 'lg' ? 'text-base' : undefined}>{item.label}</TabsTrigger>)}
    </TabsList></div>
    {items.map(item => <TabsContent key={item.id} value={item.id}>{item.panel}</TabsContent>)}
  </Tabs>;
});
