// scripts/runtime/shadcn-vue/oods-price-badge.vue
<script lang="ts">
import { defineComponent, h } from 'vue';
import { PriceBadge as Contract } from '@oods/components-vue';
import { Badge } from '@/components/ui/badge';
import { currencyMinorUnits } from '@oods/component-contracts';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsPriceBadgeAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots }: any) {
    return () => {
      const currency = props.currency ?? props.currencyCode;
      const cents = props.amountCents ?? props.unitAmountCents;
      const amount = cents === undefined ? props.amount ?? props.unitAmount : cents / currencyMinorUnits(currency, props.minorUnits);
      let formatted = 'Price';
      if (amount !== undefined && Number.isFinite(amount)) {
        try { formatted = new Intl.NumberFormat('en-US', currency ? { style: 'currency', currency: currency.toUpperCase() } : { maximumFractionDigits: 2 }).format(amount); }
        catch { formatted = `${currency?.toUpperCase() ?? ''} ${amount.toFixed(2)}`.trim(); }
      }
      return h(Badge, { ...attrs, 'data-oods-component': undefined, variant: props.emphasis === 'solid' ? 'default' : 'secondary',
        'data-oods-adapter': 'PriceBadge', 'data-price': 'true', 'data-currency': currency?.toUpperCase(), title: attrs.title ?? props.label,
      }, { default: () => slots.default?.() ?? props.label ?? props.value ?? formatted });
    };
  },
});
</script>

// scripts/runtime/shadcn/oods-price-badge.tsx
import * as React from 'react';
import type { PriceBadgeProps } from '@oods/components-react';
import { currencyMinorUnits } from '@oods/component-contracts';
import { Badge } from '@/registry/new-york-v4/ui/badge';

export const OodsPriceBadge = React.forwardRef<HTMLSpanElement, PriceBadgeProps>(function OodsPriceBadge(
  { amountCents, unitAmountCents, minorUnits, amount, unitAmount, currency, currencyCode, label, value, children,
    emphasis = 'subtle', field, amountField, currencyField, intervalField, minorUnitsParameter, ...props }, ref,
) {
  void [field, amountField, currencyField, intervalField, minorUnitsParameter];
  const cents = amountCents ?? unitAmountCents;
  const code = currency ?? currencyCode;
  const price = cents === undefined ? amount ?? unitAmount : cents / currencyMinorUnits(code, minorUnits);
  let formatted: React.ReactNode = value ?? 'Price';
  if (price !== undefined && Number.isFinite(price)) {
    if (!code) formatted = new Intl.NumberFormat(undefined, { maximumFractionDigits: 2 }).format(price);
    else try { formatted = new Intl.NumberFormat(undefined, { style: 'currency', currency: code.toUpperCase() }).format(price); }
    catch { formatted = `${code.toUpperCase()} ${price.toFixed(2)}`; }
  }
  return <Badge {...props} ref={ref} variant={emphasis === 'solid' ? 'default' : 'secondary'}
    data-oods-component={undefined} data-oods-adapter="PriceBadge" data-badge-variant="price" data-price="true" data-currency={code?.toUpperCase()}>
    {label ?? children ?? formatted}
  </Badge>;
});
