// scripts/runtime/shadcn-vue/oods-banner.vue
<script lang="ts">
import { defineComponent, h } from 'vue';
import { Banner as Contract } from '@oods/components-vue';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { getStatusPresentation } from '@oods/component-contracts';

// Reuse the shipped Vue prop defaults and event vocabulary; the rendered parts belong to the team.
export default defineComponent({
  name: 'OodsBannerAdapter',
  inheritAttrs: false,
  props: Contract.props,
  emits: Array.isArray(Contract.emits) ? Contract.emits : Object.keys(Contract.emits ?? {}),
  setup(props: any, { attrs, slots, emit }: any) {
    return () => { const presentation = getStatusPresentation(props.domain, props.status ?? 'unknown'); const tone = props.tone ?? presentation.tone; const danger = tone === 'critical' || tone === 'danger';
      return h(Alert, { ...attrs, 'data-oods-component': undefined, variant: danger ? 'destructive' : 'default', role: danger ? 'alert' : 'status', 'aria-live': danger ? 'assertive' : 'polite',
        class: [danger ? 'bg-destructive text-background dark:bg-destructive [&_*]:text-inherit' : '', attrs.class], 'data-oods-adapter': 'Banner', 'data-tone': tone,
      }, { default: () => [props.title || props.status || slots.title ? h(AlertTitle, {}, { default: () => slots.title?.() ?? (props.title || presentation.label) }) : null,
        h(AlertDescription, {}, { default: () => [props.detail ? h('p', props.detail) : null, slots.default?.() ?? props.content, slots.actions?.()] }),
        props.dismissLabel ? h(Button, { type: 'button', variant: 'ghost', 'aria-label': props.dismissLabel, onClick: () => emit('dismiss') }, { default: () => '×' }) : null,
      ] }); };

  },
});
</script>

// scripts/runtime/shadcn/oods-banner.tsx
import * as React from 'react';
import type { BannerProps } from '@oods/components-react';
import { getStatusPresentation, resolveStatusIcon, statusIconMarkup } from '@oods/component-contracts';
import { Alert, AlertTitle, AlertDescription } from '@/registry/new-york-v4/ui/alert';
import { Button } from '@/registry/new-york-v4/ui/button';

export const OodsBanner = React.forwardRef<HTMLDivElement, BannerProps>(function OodsBanner(
  { title, detail, description, content, children, status, domain = 'subscription', tone, emphasis = 'subtle', icon,
    showIcon, actions, onDismiss, dismissLabel = 'Dismiss notification', className, ...props }, ref,
) {
  const presentation = status ? getStatusPresentation(domain, status) : undefined;
  const resolvedTone = tone ?? presentation?.tone ?? 'neutral';
  const critical = resolvedTone === 'critical' || resolvedTone === 'danger';
  const heading = title ?? presentation?.label ?? status;
  const body = detail ?? description ?? children ?? content ?? presentation?.description;
  const name = resolveStatusIcon(presentation?.iconName);
  const mark = icon ?? (name ? <span aria-hidden="true" dangerouslySetInnerHTML={{ __html: statusIconMarkup(name) }} /> : null);
  const destructiveClass = critical ? 'bg-destructive text-background *:data-[slot=alert-description]:text-inherit' : undefined;
  return <Alert {...props} ref={ref} className={[destructiveClass, className].filter(Boolean).join(' ')} variant={critical ? 'destructive' : 'default'} role={critical ? 'alert' : 'status'}
    aria-live={critical ? 'assertive' : 'polite'} data-oods-component={undefined} data-oods-adapter="Banner" data-tone={resolvedTone} data-emphasis={emphasis}>
    {(showIcon ?? Boolean(mark)) ? mark : null}{heading ? <AlertTitle>{heading}</AlertTitle> : null}
    {body ? <AlertDescription>{body}</AlertDescription> : null}{actions}
    {onDismiss ? <Button type="button" variant="ghost" aria-label={dismissLabel} onClick={onDismiss}>×</Button> : null}
  </Alert>;
});
